version: '3'

services:
    # Koillection
    koillection:
        build:
            context: .
            args:
                GITHUB_RELEASE: '1.4.1'
        container_name: koillection
        restart: unless-stopped
        ports:
            - 89:80
        environment:
            - APP_ENV=prod
            - DB_DRIVER=pdo_pgsql
            - DB_NAME=koillection
            - DB_HOST=db
            - DB_PORT=5432
            - DB_USER=root
            - DB_PASSWORD=root
            - DB_VERSION=14
            - PHP_TZ=Europe/Paris
            - HTTPS_ENABLED=0
        volumes:
            - ./volumes/koillection/uploads:/uploads

    # Database : choose one of the following
    db:
        image: postgres:latest
        container_name: db
        restart: unless-stopped
        environment:
            - POSTGRES_DB=koillection
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        volumes:
            - "./volumes/postgresql:/var/lib/postgresql/data"
